build:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet publish -c Release Merthsoft.Decopolis.csproj
  artifacts:
    paths:
      - bin/Release/net8.0/publish/

docker:
  stage: deploy
  only: [master]
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination "$CI_REGISTRY_IMAGE:stable" --destination "$CI_REGISTRY_IMAGE:master-$CI_COMMIT_SHA"
